# Generated by Django 3.2.2 on 2021-05-09 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
        ('user', '0002_user_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='university.university', verbose_name='students'),
        ),
    ]
