# Generated by Django 3.2.2 on 2021-05-10 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('university', '0003_university_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=254, verbose_name='')),
                ('courses', models.ManyToManyField(to='course.Course', verbose_name='courses')),
                ('university', models.ManyToManyField(to='university.University', verbose_name='universities')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
