# Generated by Django 3.2.2 on 2021-05-13 00:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('dc06488f-fbdf-426f-bcc7-752ef0da1f55'), editable=False, unique=True),
        ),
    ]
