# Generated by Django 3.2.2 on 2021-05-13 01:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0003_alter_course_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('content', models.TextField(validators=[django.core.validators.MaxLengthValidator(2500)])),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='review author')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course', verbose_name='review course')),
                ('dislikes', models.ManyToManyField(related_name='review_dislikes', to=settings.AUTH_USER_MODEL, verbose_name='review dislikes')),
                ('likes', models.ManyToManyField(related_name='review_likes', to=settings.AUTH_USER_MODEL, verbose_name='review likes')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
