# Generated by Django 3.2.2 on 2021-05-12 01:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_university_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
