# Generated by Django 3.2.2 on 2021-05-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0005_auto_20210520_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='country',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='state',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
