name: Courseshell CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-20.04
    strategy:
      matrix:
        db: [postgres]
        python-version: [3.6, 3.7, 3.8]
        include:
          - db: postgres
            db_user: cli_db_user
            db_password: 'password'

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Start PostgreSQL
      if: matrix.db == 'postgres'
      run: |
        sudo systemctl start postgresql.service
        sudo -u postgres
        psql -c "create role cli_db_user with login password 'password';"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/courseshell_backend/requirements.txt

    - name: Run Tests
      env:
        SECRET_KEY: vz@h6kziphf$m&xxu4$dfe4bt6h8_a_!^54yup$rk*_93d1x+h
        DEV_ENV: dev
        DB_NAME: ${{ matrix.db }}
        DB_HOST: 127.0.0.1
        DB_USER: ${{ matrix.db_user }}
        DB_PASSWORD: ${{ matrix.db_password }}
        DB_PORT: 5432
      run: |
        python backend/courseshell_backend/manage.py test test user.tests.test_models
        python backend/courseshell_backend/manage.py test test user.tests.test_views
        python backend/courseshell_backend/manage.py test test user.tests.test_graphql
        python backend/courseshell_backend/manage.py test test user.tests.test_serializers
